### ISSUE TITLE
introduce flexible ranges for profile field type_date

### ISSUE THREAD

**Issue by linskipiotr** [javiexin/multiselpf#13]
At present there is only one fixed range available when defining a profile field as "type_date".
If in the registration form several profile fields like "birthday" and "startdate of membership" are used,
both will have exact the same range.

Ideally, everytime when a new profile field of "type_date" is defined,
you also would like to be able to select a unique range for that specific profile field
instead of being forced to use the at present available "hard coded" value.

**Comment by javiexin** [comment]
Done as a separate extension

**Comment by linskipiotr** [comment]
Hi Javiexin,

great !!!

Regards, Piotr
